insert into Ingredientes values(NULL,'portabella mushrooms');
insert into Ingredientes values(NULL,'radishes');
insert into Ingredientes values(NULL,'bourbon');
insert into Ingredientes values(NULL,'beans');
insert into Ingredientes values(NULL,'coconut milk');
insert into Ingredientes values(NULL,'scallops');
insert into Ingredientes values(NULL,'remoulade');
insert into Ingredientes values(NULL,'butter');
insert into Ingredientes values(NULL,'sherry');
insert into Ingredientes values(NULL,'passion fruit');
insert into Ingredientes values(NULL,'oranges');
insert into Ingredientes values(NULL,'sour cream');
insert into Ingredientes values(NULL,'bean sprouts');
insert into Ingredientes values(NULL,'bruschetta');
insert into Ingredientes values(NULL,'veal');
insert into Ingredientes values(NULL,'curry leaves');
insert into Ingredientes values(NULL,'kiwi');
insert into Ingredientes values(NULL,'eggs');
insert into Ingredientes values(NULL,'borscht');
insert into Ingredientes values(NULL,'mint');
insert into Ingredientes values(NULL,'squid');
insert into Ingredientes values(NULL,'brunoise');
insert into Ingredientes values(NULL,'mushrooms');
insert into Ingredientes values(NULL,'cashew nut');
insert into Ingredientes values(NULL,'English muffins');
insert into Ingredientes values(NULL,'vegemite');
insert into Ingredientes values(NULL,'Marsala');
insert into Ingredientes values(NULL,'grouper');
insert into Ingredientes values(NULL,'panko bread crumbs');
insert into Ingredientes values(NULL,'succotash');
insert into Ingredientes values(NULL,'chicken');
insert into Ingredientes values(NULL,'turnips');
insert into Ingredientes values(NULL,'black-eyed peas');
insert into Ingredientes values(NULL,'rice wine');
insert into Ingredientes values(NULL,'rhubarb');
insert into Ingredientes values(NULL,'sea cucumbers');
insert into Ingredientes values(NULL,'half-and-half');
insert into Ingredientes values(NULL,'rum');
insert into Ingredientes values(NULL,'grapes');
insert into Ingredientes values(NULL,'peas');
insert into Ingredientes values(NULL,'mesclun greens');
insert into Ingredientes values(NULL,'snow peas');
insert into Ingredientes values(NULL,'truffles');
insert into Ingredientes values(NULL,'habanero chilies');
insert into Ingredientes values(NULL,'sage');
insert into Ingredientes values(NULL,'lobsters');
insert into Ingredientes values(NULL,'rice paper');
insert into Ingredientes values(NULL,'maple syrup');
insert into Ingredientes values(NULL,'blackberries');
insert into Ingredientes values(NULL,'cider');
